version: "3.9"

services:
  app:
    build: .
    container_name: autenticacao_app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/autenticacao
      - JWT_SECRET=algumseguro
      - JWT_REFRESH_SECRET=outroseguro
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: autenticacao_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
